services:
    app:
        image: python:3.10.16-bullseye
        command: sleep infinity
        working_dir: /workspaces/Dev-Container-Compose
        volumes:
        - ..:/workspaces/Dev-Container-Compose
        
    ollama:
        image: ollama/ollama:latest
        container_name: ollama
        restart: unless-stopped
        ports:
            - "11434:11434"
        volumes:
            - ollama_data:/root/.ollama
            
volumes:
  ollama_data:
    driver: local
